function add_lib_dir(name)
	package.path = name.."/?.lua;"..(package.path or "")
	package.cpath = name.."/?.so;"..(package.cpath or "")
end

add_lib_dir("libs/LuaXml")
add_lib_dir("libs/luasocket")
add_lib_dir("libs/json")
add_lib_dir("libs/lpeg-0.12")

dofile("lua/functions.lua")
dofile("lua/stack.lua")
dofile("lua/error.lua")
dofile("lua/msg.lua")
dofile("lua/connect.lua")
dofile("lua/join.lua")
dofile("lua/talk.lua")
dofile("lua/quotes.lua")
dofile("lua/bitly.lua")
dofile("lua/last.lua")
dofile("lua/spam.lua")
dofile("lua/weather.lua")
